"""Initial migration.

Revision ID: 6c9b59fc92fa
Revises: 
Create Date: 2021-12-01 09:27:14.859362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9b59fc92fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('school', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('type_account', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type_account')
    op.drop_column('user', 'school')
    # ### end Alembic commands ###
