"""Initial migration.

Revision ID: 3885b4818f1d
Revises: 
Create Date: 2021-12-12 18:58:03.481977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3885b4818f1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'courses',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'courses',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
